language: node_js

node_js:
  - '10'

env:
  - COMMAND=build
  - COMMAND=test-ci

install: yarn --frozen-lockfile

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn run $COMMAND
