name: Deploy to Firebase Production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: firebase
      url: https://nodejs.dev/
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.3.0
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install NPM packages
        run: npm ci

      - uses: jongwooo/gatsby-cache@v1.4.1
        with:
          key: firebase-deployment-gatsby-ubuntu-latest

      - name: Build Gatsby
        run: npm run build-ci

      - uses: FirebaseExtended/action-hosting-deploy@v0.7.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NODEJS_INFRASTRUCTURE }}'
          channelId: live
          projectId: '${{ secrets.GCP_PROJECT_ID }}'
