name: Generate Preview

on:
  pull_request_target:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'create-preview'
    steps:

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set variables
        run: |
          echo "::set-env name=REPOSITORY::$(echo ${{ github.repository }} | cut -d/ -f2)"
          echo "::set-env name=OWNER::${{ github.repository_owner }}"
          echo "::set-env name=PR_ID::${{ github.event.number || github.event.pull_request.number }}"

      - name: Setup GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Remove create-preview label
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({
              issue_number: ${{ env.PR_ID }},
              owner: ${{ env.OWNER }},
              repo: ${{ env.REPOSITORY }},
              name: ['create-preview']
            })

      - name: Install Dependencies
        run: npm ci

      - name: Run Gatsby Build
        run: npm run build-ci
        env:
          PATH_PREFIX: ${{ env.PR_ID }}/

      - name: Run Storybook Build
        run: npm run build-storybook
        env:
          PATH_PREFIX: ${{ env.PR_ID }}/

      - name: Upload to GCS
        run: gsutil -m rsync -R public gs://staging.nodejs.dev/${{ github.event.pull_request.number }}/

      - name: Comment on PR
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: ${{ env.PR_ID }},
              owner: ${{ env.OWNER }},
              repo: ${{ env.REPOSITORY }},
              body: 'Please find a preview at: https://staging.nodejs.dev/${{ github.event.pull_request.number }}/'
            });
