name: Upload to staging

on:
  issue_comment:
    type: created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        id: comment
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const isValidPreview = (
              context.payload.issue.pull_request &&
              context.payload.comment.body === '/preview'
            );
            return isValidPreview;

      - uses: actions/checkout@v2
        if: steps.comment.outputs.result == 'true'

      - name: Checkout Git Branch
        if: steps.comment.outputs.result == 'true'
        run: |
          git fetch origin +refs/pull/${{ github.event.issue.number }}/merge
          git checkout FETCH_HEAD

      - name: Setup GCloud
        if: steps.comment.outputs.result == 'true'
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: actions/cache@v1
        if: steps.comment.outputs.result == 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true' && steps.comment.outputs.result == 'true'
        run: npm ci

      - name: Run Gatsby Build
        if: steps.comment.outputs.result == 'true'
        run: npm run build-ci
        env:
          PATH_PREFIX: ${{ github.event.issue.number }}/

      - name: Upload to GCS
        if: steps.comment.outputs.result == 'true'
        run: gsutil -m rsync -R public gs://staging.nodejs.dev/${{ github.event.issue.number }}/

      - name: Comment on PR
        if: steps.comment.outputs.result == 'true'
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Please find a preview at: https://staging.nodejs.dev/${{ github.event.issue.number }}/'
            });
